export interface SpeciesInfo {
  description: string;
  tempRange: [number, number];
  tempLabel: string;
  bestPressure: string;
  bestLight: string;
  bestTide: string;
  primaryDriver: string;
  secondaryDriver: string;
  agn: string[];
  sluk: string[];
  teknikktips: string;
  fargetips?: string;
}

export const SPECIES_INFO: Record<string, SpeciesInfo> = {
  Torsk: {
    description: 'Torsken er Norges viktigste matfisk og finnes langs hele kysten. Den er mest aktiv når trykket faller, noe som utløser beiteatferd i stimer. Beste fiske skjer i kaldt vann mellom 4 og 8 °C, særlig på dypt vann om vinteren.',
    tempRange: [4, 8], tempLabel: '4–8 °C', bestPressure: 'Fallende', bestLight: 'Lavt lys', bestTide: 'Stigende',
    primaryDriver: 'Lufttrykk', secondaryDriver: 'Vanntemperatur',
    agn: ['Makrellfilet', 'Hel agnsild', 'Strandkrabbe', 'Børstemark', 'Fjæremark'],
    sluk: ['Gummisild/jig', 'Pilk 40–100g', 'Sildesluker'],
    teknikktips: 'Varier innsveivingshastigheten med hyppige stopp – imiterer et skadet byttedyr og trigger huggrefleksen.',
    fargetips: 'Bunnbeiting: gul/rød · Sildebeiting: sølv/blank',
  },
  Kveite: {
    description: 'Kveita er Norges største flatfisk og kan bli over 300 kg. Den er primært et dypvannsdyr som følger tidevannets bevegelser for å jakte på annen fisk. Stor og mektig – kveite krever tålmodighet og riktig utstyr.',
    tempRange: [4, 10], tempLabel: '4–10 °C', bestPressure: 'Stabilt', bestLight: 'Lavt lys', bestTide: 'Stigende',
    primaryDriver: 'Tidevann', secondaryDriver: 'Månefase',
    agn: ['Hel agnsild', 'Makrellfilet'],
    sluk: ['Store gummijigger (sei/sild-imitasjon)'],
    teknikktips: 'Vent 2–3 sekunder etter hugget – kveita smaker på agnet før den sluke det. Sirkelkrok str. 8/0 anbefales.',
  },
  Sei: {
    description: 'Seien er en hurtig og stimfisk som jakter aktivt i vannmassene. Den trives best i moderat strøm og er særlig aktiv i tusmørket når lyset er lavt. Sei finnes langs hele norskekysten og er en populær sportsfisk.',
    tempRange: [6, 14], tempLabel: '6–14 °C', bestPressure: 'Fallende', bestLight: 'Tusmørke', bestTide: 'Stigende',
    primaryDriver: 'Strøm', secondaryDriver: 'Lysnivå',
    agn: [],
    sluk: ['Kompakte sildesluker', 'Pilk', 'Gummimakk'],
    teknikktips: 'Sveiv så raskt som mulig – fart trigger jaktinstinktet og gir fisken ikke tid til å inspisere agnet kritisk.',
    fargetips: 'Gummimakk: rød, hvit og selvlysende grønn er klassiske valg',
  },
  Hyse: {
    description: 'Hysen er nær beslektet med torsken, men slankere og med et karakteristisk sort skulderflekkmerke. Den er mest aktiv ved fallende lufttrykk og lever nær bunnen på sandbunn og skjellsand. Hysen gir god kamp på lett utstyr.',
    tempRange: [4, 10], tempLabel: '4–10 °C', bestPressure: 'Fallende', bestLight: 'Dagslys', bestTide: 'Stigende',
    primaryDriver: 'Lufttrykk', secondaryDriver: 'Bunntype',
    agn: ['Reke', 'Blåskjell', 'Fjæremark'],
    sluk: ['Takler med perler og spinnerblader'],
    teknikktips: 'Hysa er nysgjerrig på farger og lys – bruk "juggel" med perler og spinnerblader for å øke fangstraten.',
    fargetips: 'Attraktorer: rosa, hvit og gul er mest effektive · Selvlysende detaljer øker fangst',
  },
  Lange: {
    description: 'Langen er en langstrakt torskefisk som lever på dypt, hardt bunn. Den foretrekker stille vann med lite strøm og er særlig aktiv ved stigende tidevann. Langens lange kropp og nennsom bit krever en viss teknikk.',
    tempRange: [4, 10], tempLabel: '4–10 °C', bestPressure: 'Stabilt', bestLight: 'Lavt lys', bestTide: 'Stigende',
    primaryDriver: 'Tidevann', secondaryDriver: 'Vanndybde',
    agn: ['Makrellfilet', 'Sildfilet (store biter)'],
    sluk: ['Tunge lodd 300–800g', 'Selvlysende slanger', 'Blekksprutimitasjoner'],
    teknikktips: 'Hold agnet 2–5 meter over bunnen og i bevegelse – lange jakter aktivt, i motsetning til den stasjonære brosma.',
  },
  Brosme: {
    description: 'Brosmen er en dypvannsfisk med lang ryggfinne og kraftig barbel under haken. Den holder til på steinbunn og korallrev på dypt vann. Brosme er en seig fighter og smaker utmerket røkt eller saltet.',
    tempRange: [4, 8], tempLabel: '4–8 °C', bestPressure: 'Stabilt', bestLight: 'Lavt lys', bestTide: 'Stigende',
    primaryDriver: 'Tidevann', secondaryDriver: 'Vanndybde',
    agn: ['Makrell (ferskt)', 'Sild (ferskt)'],
    sluk: ['Tunge lodd', 'Selvlysende blekksprutimitasjoner'],
    teknikktips: 'La agnet ligge helt nede ved bunnen – brosma beveger seg lite vertikalt og er svært stasjonær.',
  },
  Uer: {
    description: 'Ueren er en langlivende rødfisk som kan bli over 100 år gammel. Den er nattaktiv og trives i stabilt vær med lite bevegelse i vannmassene. Store uer holder til på dypt vann i fjordene og langs ytterkysten.',
    tempRange: [4, 8], tempLabel: '4–8 °C', bestPressure: 'Stabilt', bestLight: 'Natt', bestTide: '—',
    primaryDriver: 'Lysnivå', secondaryDriver: 'Lufttrykk',
    agn: ['Reke', 'Makrell', 'Sild'],
    sluk: ['Uersnik (lange takler, mange kroker)', 'Selvlysende kroker/detaljer'],
    teknikktips: 'Ueren står i tette stimer mange meter over bunnen – søk med lange takler (opptil 20m) gjennom hele vannsøylen.',
  },
  Steinbit: {
    description: 'Steinbiten har et stort, avrundet hode med kraftige tenner som kan knuse skjell og krabber. Den holder til på steinbunn i kaldt vann og er aktiv året rundt. Steinbiten er lite sky og biter godt i stabilt vær.',
    tempRange: [4, 10], tempLabel: '4–10 °C', bestPressure: 'Stabilt', bestLight: 'Lavt lys', bestTide: 'Stigende',
    primaryDriver: 'Vanntemperatur', secondaryDriver: 'Tidevann',
    agn: ['Kamskjell', 'Blåskjell', 'Fiskefilet'],
    sluk: ['Gummifisk (ekstremt sakte)', 'Bunnmeite med bom og slep'],
    teknikktips: 'Spinnerblader og tunge perler kan irritere steinbit til hugg – den er territorial og aggressiv.',
  },
  Makrell: {
    description: 'Makrellen er en rask, stimfisk som inntar norske kystfarvann om sommeren når vannet er varmt. Den biter best i lett til moderat bris som rører overflaten. Makrell er kjent for sine intense kamper og er utmerket til mat.',
    tempRange: [12, 24], tempLabel: '12–24 °C', bestPressure: 'Stabilt', bestLight: 'Dagslys', bestTide: '—',
    primaryDriver: 'Vanntemperatur', secondaryDriver: 'Vind',
    agn: ['Sild', 'Makrellbiter'],
    sluk: ['Sildesluker 15–28g', 'Makrellharpe/hekler (5–10 kroker)'],
    teknikktips: 'Hold sluken rett under overflaten med små rykk i stanga – øker huggvilligheten markant.',
  },
  Rødspette: {
    description: 'Rødspetta er en fargerik flatfisk med karakteristiske oransje prikker på oversiden. Den finnes på sandbunn i grunne kystfarvann og er særlig aktiv ved stigende tidevann. Rødspette er en delikatesse og gir god sport på lettutstyr.',
    tempRange: [8, 16], tempLabel: '8–16 °C', bestPressure: 'Stabilt', bestLight: 'Dagslys', bestTide: 'Stigende',
    primaryDriver: 'Tidevann', secondaryDriver: 'Bunntype',
    agn: ['Sandorm/børstemark', 'Reke', 'Makrellstrimmel (hvitt bukskin)'],
    sluk: ['Perler og spinnerblader som attraktorer'],
    teknikktips: 'Dunk loddet lett i bunnen for å virvle opp sedimenter – tiltrekker rødspettas nysgjerrighet.',
    fargetips: 'Attraktorer: hvit, perlemor, gul og rød er mest effektive',
  },
  Lomre: {
    description: 'Lomra er den minste av de norske flyndrefiskene og lever på sandbunn i rolige, grunne farvann. Den er lite krevende å fiske etter, men krever fint agn nær bunnen. Lomre er god på tallerkenen trass i beskjeden størrelse.',
    tempRange: [8, 16], tempLabel: '8–16 °C', bestPressure: 'Stabilt', bestLight: 'Dagslys', bestTide: '—',
    primaryDriver: 'Bunntype', secondaryDriver: 'Strøm',
    agn: ['Blåskjell (små biter)', 'Reke'],
    sluk: ['Kroker str. 4–8 (meget små)'],
    teknikktips: 'La agnet ligge helt stille – lomra suger inn byttedyr fra bunnen og responderer ikke på bevegelse.',
  },
  Sandflyndre: {
    description: 'Sandflyndra ligner lomra, men er noe mer langstrakt og foretrekker litt dypere sandbunn. Den er et byttedyr for kveite og torsk, men kan også fiskes på lett snøre med mark. Sandflyndre gir god smak fra norske kystfarvann.',
    tempRange: [8, 16], tempLabel: '8–16 °C', bestPressure: 'Stabilt', bestLight: 'Dagslys', bestTide: '—',
    primaryDriver: 'Bunntype', secondaryDriver: 'Strøm',
    agn: ['Reke', 'Fiskestrimler', 'Mark'],
    sluk: ['Kroker str. 4–1'],
    teknikktips: 'Løft agnet sakte og sett det ned igjen med jevne mellomrom – sandflyndra liker agn i bevegelse.',
  },
  Sild: {
    description: 'Silden vandrer i store stimer langs norskekysten og er en nøkkelart i havøkosystemet. Den er mest aktiv i kjølig til temperert vann og samler seg gjerne i store stimer rundt fullmåne og nymåne. Sild er en klassisk norsk matfisk.',
    tempRange: [6, 14], tempLabel: '6–14 °C', bestPressure: 'Stabilt', bestLight: 'Natt', bestTide: '—',
    primaryDriver: 'Vanntemperatur', secondaryDriver: 'Månefase',
    agn: [],
    sluk: ['Sildehekler (reflekterende)', 'Planktonimitasjoner'],
    teknikktips: 'Bruk rig med mange små kroker og fint snøre – heklene skal imitere plankton og småfisk i stimen.',
  },
  Laks: {
    description: 'Laksen er en legendarisk sportsfisk som returnerer til elven der den ble klekket. I sjøen biter laksen best i tusmørket ved fallende lufttrykk. Den er en kraftig fighter som krever godt utstyr og tålmodighet fra fiskeren.',
    tempRange: [8, 18], tempLabel: '8–18 °C', bestPressure: 'Fallende', bestLight: 'Tusmørke', bestTide: 'Stigende',
    primaryDriver: 'Lysnivå', secondaryDriver: 'Lufttrykk',
    agn: ['Sild', 'Brisling (ved dorging)'],
    sluk: ['Buch Salmon (gull/kobber-rød)', 'Trønderskjea', 'Møresilda 22–55g'],
    teknikktips: 'Velg slukfarge etter elvas fargetone – matchen mellom sluken og vannets farge er avgjørende.',
    fargetips: 'Klar elv: sølv/blå · Cognac-farget: gull/kobber · Flomvann: oransje/rød',
  },
  Sjøørret: {
    description: 'Sjøørreten er brunørretens sjøvandrende form og finnes langs kysten i saltvann deler av året. Den er svært temperert og biter best i lavt lys ved fallende trykk. Sjøørret er kjent for ville hopp og spektakulære kamper på lett utstyr.',
    tempRange: [8, 16], tempLabel: '8–16 °C', bestPressure: 'Fallende', bestLight: 'Tusmørke', bestTide: 'Stigende',
    primaryDriver: 'Lysnivå', secondaryDriver: 'Lufttrykk',
    agn: ['Pattegrisen-flue (reke)', 'Jiggy-flue (småfisk)'],
    sluk: ['Møresilda holografisk', 'Skjesluker (Toby, Søvik Auren)', 'Kystwobblere'],
    teknikktips: 'Spinnstopp er kritisk – la sluken synke 2–3 sek med jevne mellomrom. De fleste hugg kommer ved retningsskifte.',
    fargetips: '7–17 °C: holografisk sølv/sort eller sølv/blå · Kaldt vann: rosa, oransje eller hvit/fluo',
  },
  Sjørøye: {
    description: 'Sjørøya er den nordligste av de anadrome laksefiskene og trives i kaldt arktisk vann. Den vandrer mellom ferskvann og saltvann og er kjent for sine intense farger i gytetiden. Sjørøye er en delikatesse med fast, rosa kjøtt.',
    tempRange: [2, 14], tempLabel: '2–14 °C', bestPressure: 'Stabilt', bestLight: 'Lavt lys', bestTide: 'Stigende',
    primaryDriver: 'Vanntemperatur', secondaryDriver: 'Saltholdighet',
    agn: [],
    sluk: ['Astro Vibe', 'Hybridmodeller sluk/wobbler', 'Fargerike kystsluker'],
    teknikktips: 'Lignende teknikk som sjøørret – spinnstopp med 2–3 sekunders pause. Mest knyttet til fjordsystemer i Nord-Norge.',
    fargetips: 'Fargerike og kontrasterende varianter er generelt mest effektive',
  },
  Ørret: {
    description: 'Brunørreten er en av Norges mest ettertraktede sportsfisker og finnes i elver og innsjøer over hele landet. Den er best aktiv ved fallende lufttrykk og biter godt i det ideelle temperaturvinduet på 8–14 °C. Ørreten er en taktisk og krevende fisk.',
    tempRange: [8, 14], tempLabel: '8–14 °C', bestPressure: 'Fallende', bestLight: 'Tusmørke', bestTide: '—',
    primaryDriver: 'Lufttrykk', secondaryDriver: 'Vanntemperatur',
    agn: ['Parachute Adams (flue)', 'CdC and Elk (flue)', 'Maur/Stankelbein (flue)', 'Gold Ribbed Hares Ear (nymfe)'],
    sluk: ['Møreungen Nordlys 12g', 'Sølvkroken Spesial Classic 10g', 'Aura Flake 12g'],
    teknikktips: 'Aura Flake med "discokule"-overflate er effektiv under nesten alle lysforhold. Match fluetype til årstidens insektklekk.',
    fargetips: 'Klart vann/sol: naturlige farger og sølv · Grumsete/overskyet: gull, kobber og fluorescerende',
  },
  Røye: {
    description: 'Røya er en kaldtvannsart som trives best i dype, klare innsjøer. Den biter godt ved fallende trykk i kjølig vann og er særlig aktiv om høsten i gytetiden. Røye er Norges vakreste innlandsfisk med sine karakteristiske farger.',
    tempRange: [4, 8], tempLabel: '4–8 °C', bestPressure: 'Fallende', bestLight: 'Lavt lys', bestTide: '—',
    primaryDriver: 'Lufttrykk', secondaryDriver: 'Vanntemperatur',
    agn: ['Insektsimitasjoner (flue)'],
    sluk: ['Søvik-Skeia (kobber/rød)', 'Åsenskjea (kobber/rød)'],
    teknikktips: 'Kobberfarger er overlegne for røye, særlig ved lavt lys og om kvelden.',
    fargetips: 'Kveld/lavt lys: kobber og rød · Dagslys: naturlige ørretfarger',
  },
  Abbor: {
    description: 'Abboren er en av de vanligste innlandsfiskene i Norge og kjennes igjen på de vertikale stripene langs kroppen. Den er varmtvannsfisk og biter best om sommeren i tusmørket. Abbor samler seg gjerne rundt vegetasjon og strukturer nær land.',
    tempRange: [15, 22], tempLabel: '15–22 °C', bestPressure: 'Stabilt', bestLight: 'Tusmørke', bestTide: '—',
    primaryDriver: 'Vanntemperatur', secondaryDriver: 'Lysnivå',
    agn: [],
    sluk: ['Gummiappon 5–13 cm', 'Spinnere (Mepps/Vibrax)', 'Rapala X-Rap wobbler'],
    teknikktips: 'Spinnere sender ut sterke trykkbølger – ideelt for å lokalisere aktiv fisk i stimen raskt.',
    fargetips: 'Imiterer byttedyr: grønt, brunt, oransje · Aggresjon: gult og rød',
  },
  Gjedde: {
    description: 'Gjedda er toprøveren i norske innsjøer og elver med sitt karakteristiske andesnute og kraftige kropp. Den er en ambushjeger som liker lavt lys og venter stille på byttet. Store gjedder kan veie over 10 kg og er en av de mest spennende sportsfiskene i ferskvann.',
    tempRange: [10, 20], tempLabel: '10–20 °C', bestPressure: 'Fallende', bestLight: 'Lavt lys', bestTide: '—',
    primaryDriver: 'Vanntemperatur', secondaryDriver: 'Lysnivå',
    agn: ['Død fisk 15–30 cm (sild/makrell/mort)'],
    sluk: ['Abu Garcia Atom (stor skjesluk)', 'Store wobblere 15–25 cm'],
    teknikktips: 'Bruk alltid wire/stålfortom – gjeddas tenner kutter vanlig snøre umiddelbart.',
    fargetips: 'Uklart vann: sterke farger (Fire Tiger) · Klart vann: naturlige farger (abbor/gjeddemønster)',
  },
  Harr: {
    description: 'Harren er kjent for sin imponerende seildorsalfinne og finnes i klare, raske elver med god vannkvalitet. Den er en delikat fluefisk som stiger til overflaten for å ta insekter. Harr er krevende å lure og belønner deg med spektakulære hopp.',
    tempRange: [8, 14], tempLabel: '8–14 °C', bestPressure: 'Stabilt', bestLight: 'Tusmørke', bestTide: '—',
    primaryDriver: 'Vanntemperatur', secondaryDriver: 'Lufttrykk',
    agn: ['Red Tag (flue)', 'Superpuppan (flue)', 'BH nymfer (gull/kobberhode)'],
    sluk: ['Spinnere str. 0–2'],
    teknikktips: 'Red Tag med rød "tag" er harrflue nr. 1 – den røde detaljen fungerer som en kraftig visuell trigger.',
    fargetips: 'Tidlig sesong: blank/sølv spinner · Høst: diskré og naturlige farger',
  },
};
